name: Deploy
on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      IMAGE: "ghcr.io/${{ github.repository }}"
    steps:
      - uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
      - run: docker build -t $IMAGE:${{ github.ref }} $IMAGE:latest .
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push $IMAGE:${{ github.ref }}
      - run: docker push $IMAGE:latest
