name: main
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.15
      - run: deno fmt --check
      - run: deno lint
  
  test:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.15
      - run: deno test --import-map=import_map.json --jobs 4
  
  build:
    runs-on: ubuntu-20.04
    needs: test
    env:
      IMAGE: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
    steps:
      - uses: actions/checkout@v2
      - run: "docker build -t $IMAGE ."
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push $IMAGE
