name: Quality
on:
  push:
    branches-ignore: [ main ]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.15
      - run: deno fmt --check
      - run: deno lint

  test:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.15
      - run: deno test --import-map=import_map.json --jobs 4

  analyze:
    runs-on: ubuntu-20.04
    needs: test
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: typescript
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

